[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
Event_Marketplace = "2FmHJnC5o3ydRYLqsABrNvgkt839gon6r5WyTGuHxjjR"

[programs.devnet]
Event_Marketplace = "2FmHJnC5o3ydRYLqsABrNvgkt839gon6r5WyTGuHxjjR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run"
